// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // sessionStorage (not localStorage) so a login lasts only for the current
    // browser session: it survives page reloads/navigation, but the user must
    // sign in again after they close the tab/browser and reopen the site.
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Parse the recovery/confirmation token from the URL after an email link,
    // so the password-reset page gets a session automatically.
    detectSessionInUrl: true,
  }
});